sonar.projectKey=btech-software_especialista-contabilidade
sonar.organization=btech-software
sonar.sources=especialista_contabilidade,frontend/src
sonar.tests=tests
sonar.test.inclusions=tests/**,frontend/src/**/*.spec.ts
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
sonar.exclusions=tests/**,frontend/node_modules/**,frontend/src/index.html,frontend/src/**/*.html,especialista_contabilidade/static/**
sonar.coverage.exclusions=tests/**,especialista_contabilidade/static/**
